swagger: '2.0'
info:
  title: Proxy API Service
  x-ibm-name: proxy-api-service
  version: 1.0.0
  description: This API is a proxy API to connect to Backend as a Weather report.
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          version: 2.3.0
          title: invoke
          backend-type: detect
          header-control:
            type: blocklist
            values: []
          parameter-control:
            type: allowlist
            values: []
          http-version: HTTP/1.1
          timeout: 60
          verb: keep
          persistent-connection: true
          cache-response: protocol
          cache-ttl: 900
          graphql-send-type: detect
          target-url: https://backend..com/genareteReport
          chunked-uploads: true
          websocket-upgrade: false
          stop-on-error:
            - ConnectionError
          output: paymentResponse
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
  application-authentication: {}
basePath: /v1
paths:
  /getWeatherReport:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecret:
    type: apiKey
    x-key-type: client_secret
    name: X-IBM-Client-Secret
    in: header
security:
  - clientID: []
    clientSecret: []
schemes:
  - https
consumes:
  - application/xml
